-- --------------------------------------------------------
-- 호스트:                          192.168.127.128
-- 서버 버전:                        5.6.35 - MySQL Community Server (GPL)
-- 서버 OS:                        Linux
-- HeidiSQL 버전:                  9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- WSDB 데이터베이스 구조 내보내기
CREATE DATABASE IF NOT EXISTS `WSDB` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `WSDB`;

-- 테이블 WSDB.ERWN_LOGG 구조 내보내기
CREATE TABLE IF NOT EXISTS `ERWN_LOGG` (
  `LOGG_SEQN` int(11) NOT NULL AUTO_INCREMENT COMMENT '시퀀스',
  `SRVR_CATE` varchar(10) NOT NULL COMMENT '서버 종류',
  `LOGG_LEVL` varchar(20) NOT NULL COMMENT '로그 레벨',
  `LOGG_CONT` varchar(100) NOT NULL COMMENT '로그 내용',
  `INST_DATE` datetime NOT NULL COMMENT '삽입 시간',
  PRIMARY KEY (`LOGG_SEQN`)
) ENGINE=InnoDB AUTO_INCREMENT=52010 DEFAULT CHARSET=utf8 COMMENT='Server Error Log';

-- 내보낼 데이터가 선택되어 있지 않습니다.
-- 함수 WSDB.INSERT_LOG_MESSAGE 구조 내보내기
DELIMITER //
CREATE DEFINER=`WS`@`%` FUNCTION `INSERT_LOG_MESSAGE`(
	`_SRVR_CATE` VARCHAR(10),
	`_LOGG_LEVL` VARCHAR(20)


,
	`_LOGG_CONT` VARCHAR(100)



) RETURNS text CHARSET utf8
BEGIN
DECLARE MAXI_NUMB INT;
DECLARE INST_SUCC INT;
SELECT MAX(LOGG_SEQN) INTO MAXI_NUMB
FROM ERWN_LOGG;
INSERT INTO ERWN_LOGG(
	LOGG_SEQN,
	SRVR_CATE,
	LOGG_LEVL,
	LOGG_CONT,
	INST_DATE
)VALUES(
	NULL,
	_SRVR_CATE,
	_LOGG_LEVL,
	_LOGG_CONT,
	NOW()
);
SELECT COUNT(1) INTO INST_SUCC
FROM ERWN_LOGG
WHERE 1=1
AND LOGG_SEQN = MAXI_NUMB + 1;
IF(INST_SUCC = 1) THEN
RETURN 'success';
ELSE
RETURN 'fail';
END IF;
END//
DELIMITER ;

-- 프로시저 WSDB.INSERT_USERINFO_MESSAGE 구조 내보내기
DELIMITER //
CREATE DEFINER=`WS`@`%` PROCEDURE `INSERT_USERINFO_MESSAGE`(
	IN `USERIDNT` VARCHAR(50),
	IN `USERPSWD` VARCHAR(100),
	IN `USERMAIL` VARCHAR(50),
	OUT `ISSUCCESS` VARCHAR(50),
	OUT `RESULTTEXT` TINYTEXT



)
    COMMENT '유저 회원가입'
BEGIN
DECLARE USERCONT INT;
SELECT COUNT(1) INTO USERCONT
FROM USER_INFO
WHERE 1=1
AND USER_IDNT = USERIDNT;
	
IF(USERCONT = 0) THEN
INSERT INTO USER_INFO(
USER_SEQN,
USER_IDNT,
USER_PSWD,
USER_MAIL,
INPT_DATE
)VALUES(
NULL,
USERIDNT,
USERPSWD,
USERMAIL,
NOW());
SELECT COUNT(1) INTO USERCONT
FROM USER_INFO
WHERE 1=1
AND USER_IDNT = USERIDNT;
IF(USERCONT = 1) THEN
SET ISSUCCESS = 'true';
SET RESULTTEXT = 'Success.';
ELSE
SET ISSUCCESS = 'false';
SET RESULTTEXT = 'Temporary Error.';
END IF;
ELSE
SET ISSUCCESS = 'fail';
SET RESULTTEXT = 'Exit ID.';
END IF;
END//
DELIMITER ;

-- 테이블 WSDB.USER_INFO 구조 내보내기
CREATE TABLE IF NOT EXISTS `USER_INFO` (
  `USER_SEQN` int(11) NOT NULL AUTO_INCREMENT,
  `USER_IDNT` varchar(50) NOT NULL DEFAULT '0',
  `USER_PSWD` varchar(100) NOT NULL DEFAULT '0',
  `USER_MAIL` varchar(50) NOT NULL DEFAULT '0',
  `INPT_DATE` datetime NOT NULL,
  PRIMARY KEY (`USER_SEQN`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 COMMENT='유저 개인 정보';

-- 내보낼 데이터가 선택되어 있지 않습니다.
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
