-- 마지막으로 실행한 IOCP 서버에서 나온 로그
SELECT * FROM ERWN_LOGG WHERE 1=1
AND SRVR_CATE = 'IOCP'
AND INST_DATE >=
(SELECT MAX(INST_DATE) FROM ERWN_LOGG WHERE 1=1
AND SRVR_CATE = 'IOCP'
AND LOGG_CONT = 'Database Connect Success');